### ISSUE TITLE
Module RNCColorPicker requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`.

### ISSUE THREAD

**Issue by chaehonglee** [Naturalclar/react-native-color-picker-ios#310]
<img src="https://user-images.githubusercontent.com/31965990/194731979-a35b1083-19b4-4383-94db-62b46c78fee9.png" width="300px">

Hello, I am getting the above error while using the module. How should I resolve this warning?

## Environment
```
react-native info

System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 173.48 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /opt/homebrew/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.0 => 0.68.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by Tommkruix** [comment]
I started getting this issue as well; `Module RNCColorPicker requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.`. Using `"react-native": "0.71.8",
    "react-native-color-picker-ios": "^0.1.2"`

**Comment by surri** [comment]
It seems that it hasn't been released yet

https://github.com/Naturalclar/react-native-color-picker-ios/pull/6

**Comment by anup-a** [comment]
Hi @Naturalclar, looks like related PR has been merged, but no release has been made since. Could you please create a new tag ?

Thanks.

**Comment by Naturalclar** [comment]
@anup-a thanks for the ping and sorry for the delay! 
ive just released a new version with the fix 🚀 
https://github.com/Naturalclar/react-native-color-picker-ios/releases/tag/v0.1.3
