### ISSUE TITLE
Expo support

### ISSUE THREAD

**Issue by matthewhilton** [Naturalclar/react-native-color-picker-ios#8]
I am attempting to use this library on an Expo project (running on IOS), but I am running into the following error: 
`TypeError: null is not an object (evaluating 'RNCColorPicker.showColorPicker')`

I have recreated the problem on an [Expo snack](https://snack.expo.io/@unexpectederr/react-native-color-picker-ios-problem). Is there any way this library could work on Expo? It looks really good so far.

**Comment by Naturalclar** [comment]
@unxpctederr 
Thanks for raising the issue.
Unfortunately, there isn't a way to make this library work for managed workflow of expo.
In order to use this library in expo, you would have to run `expo eject` in your project to switch to bare workflow.

**Comment by yasir-lcs** [comment]
> I am attempting to use this library on an Expo project (running on IOS), but I am running into the following error: `TypeError: null is not an object (evaluating 'RNCColorPicker.showColorPicker')`
> 
> I have recreated the problem on an [Expo snack](https://snack.expo.io/@unexpectederr/react-native-color-picker-ios-problem). Is there any way this library could work on Expo? It looks really good so far.

Solution available in #56
